// ajax and loading actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Auth actions
export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';

// User actions
export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_IS_ADMIN_SUCCESS = 'USER_IS_ADMIN_SUCCESS';

// Chapters actions
export const CHAPTERS_LOAD_CALL = "CHAPTERS_LOAD_CALL";
export const CHAPTERS_LOAD_SUCCESS = "CHAPTERS_LOAD_SUCCESS";
export const CHAPTER_SWITCH = "CHAPTER_SWITCH";
export const CHAPTER_CLEAR_STATE = "CHAPTER_CLEAR_STATE";

// Heroes actions
export const HERO_CREATE_SUCCESS = "HERO_CREATE_SUCCESS";
export const HERO_CREATE_FAIL = "HERO_CREATE_FAIL";
export const HEROES_LOAD_SUCCESS = "HERO_CREATE_FAIL";

// Stories actions
export const STORY_CREATE_SUCCESS = "STORY_CREATE_SUCCESS";
export const STORY_CREATE_FAIL = "STORY_CREATE_FAIL";
export const STORIES_LOAD_SUCCESS = "STORIES_CREATE_FAIL";

//currentStory
export const CURRENT_STORY_CLEAR = "CURRENT_STORY_CLEAR";
export const CURRENT_STORY_POTENTIAL_RECRUIT_LOAD = "CURRENT_STORY_POTENTIAL_RECRUIT_LOAD";
export const CURRENT_STORY_POTENTIAL_RECRUIT_CLEAR = "CURRENT_STORY_POTENTIAL_RECRUIT_CLEAR";
export const CURRENT_STORY_HERO_LOAD = "CURRENT_STORY_HERO_LOAD";
export const CURRENT_STORY_HEROES_CLEAR= "CURRENT_STORY_HEROES_CLEAR";
export const CURRENT_STORY_SET_HERO= "CURRENT_STORY_SET_HERO";
